### ISSUE TITLE
Ad Soyad ve Ata adini boyuk herfle yazdiqda axtaris islemir

### ISSUE THREAD

**Issue by nurlanmemmedov** [emilpyp/studentsearch#2]

**Comment by emilpyp** [comment]
daha etrafli melumat veredinde zehmet olmasa.
islemelidir, cunki input alanda ve saxlayanda hemise lowercase edirem.

**Comment by nurlanmemmedov** [comment]
aha anladim burda tek problem qalir onda print edende datalari ilk herfleri boyutmek lazimdir
